import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxWrapper from "@/redux/ReduxWrapper";
import PublicLayout from "@/layouts/PublicLayout";
import { Suspense } from "react";
import Loader from "@/components/Loader";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxWrapper>
    <html lang="en">
      <body className={`${inter.className} bg-[--bg-primary]`}>
        {/* <Header/> */}
          <PublicLayout>
            <Suspense fallback={<Loader/>}>
        {children}
            </Suspense>
          </PublicLayout>
        {/* <Footer/>
         */}
        </body>
        <Script src="https://checkout.razorpay.com/v1/checkout.js"></Script> 
    </html>
    </ReduxWrapper>
  );
}
